### ISSUE TITLE
No audio

### ISSUE THREAD

**Issue by DefKorns** [fhoedemakers/pico-infonesPlus#18]
I'm using Pimoroni Pico DV Demo Base and i can't get audio through hdmi nor from the audio out jack.

could this be a problem with the soldering?

**Comment by fhoedemakers** [comment]
Sorry to hear sound is not working.

I assume you are getting a picture without a problem.

Audio through the audio jack does not work since it is not programmed to do so. Audio works only through HDMI. 

I'm not sure if it has to do with the soldering. Did you use a pico with pre-soldered headers or did you solder the headers yourself? I that case reflow them with a soldering iron.
Can you try another HDMI cable?
When the DV Demo Base is connected through a hdmi switch, try to connect it directly.

**Comment by DefKorns** [comment]
Hi @fhoedemakers 

`I assume you are getting a picture without a problem.`
yes i'm getting picture without any problem. 

`Did you use a pico with pre-soldered headers or did you solder the headers yourself?`
I've soldered the headers myself.

`Can you try another HDMI cable?` 
Sure, but the cable works fine with the ps4.

`When the DV Demo Base is connected through a hdmi switch, try to connect it directly.`
It's already connected directly.

I'll recheck everything once more and keep you updated

**Comment by DefKorns** [comment]
@fhoedemakers i reflowed all pins and now i have sound.

Thank you

**Comment by fhoedemakers** [comment]
Great to hear it works!
